server:
  port: 8082

spring:
  application:
    name: xkw-rocketmq-demo
  datasource:
    url: jdbc:mysql://localhost:3306/rocketmq_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: rootroot
    hikari:
      pool-name: springHikariCP
      connection-timeout: 5000
      minimum-idle: 5
      idle-timeout: 180000
      max-lifetime: 1800000
      maximum-pool-size: 50

rocketmq:
  name-server: 10.1.1.28:8876;10.1.1.60:8876;10.1.25.126:8876
  consumer:
    namespace: dev
    access-key: urockmq
    secret-key: ka9inWuHInq9PBPnhLuH

xkw-rocketmq:
  producer:
    enable: false
  consumer:
    enable: true

logging:
  config: classpath:logback-config.xml
  level:
    com.xkw.bcom.rocketmq.core: debug

log:
  home: ./data/logs/xkw-rocketmq-consumer-demo
  root-level: INFO
  mybatis-log: false

