#mybatis配置
#mybatis:
#  mapper-locations: classpath:henu/soft/*.xml    # mapper映射文件位置
#  type-aliases-package: henu.soft.tomato.model    # 实体类所在的位置
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #用于控制台打印sql语句

#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: heun.soft.tomato.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
